-- UNO game history schema (H2-compatible)
-- Hibernate auto-applies this structure; the script documents the model.

CREATE TABLE IF NOT EXISTS players (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS games (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    started_at TIMESTAMP NOT NULL,
    ended_at TIMESTAMP NOT NULL,
    winner_id BIGINT,
    CONSTRAINT fk_games_winner FOREIGN KEY (winner_id) REFERENCES players(id)
);

CREATE TABLE IF NOT EXISTS rounds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    round_number INT NOT NULL,
    winner_id BIGINT NOT NULL,
    points_awarded INT NOT NULL,
    ended_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_rounds_game FOREIGN KEY (game_id) REFERENCES games(id),
    CONSTRAINT fk_rounds_winner FOREIGN KEY (winner_id) REFERENCES players(id)
);

CREATE TABLE IF NOT EXISTS scores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    game_id BIGINT NOT NULL,
    player_id BIGINT NOT NULL,
    total_score INT NOT NULL,
    CONSTRAINT fk_scores_game FOREIGN KEY (game_id) REFERENCES games(id),
    CONSTRAINT fk_scores_player FOREIGN KEY (player_id) REFERENCES players(id),
    CONSTRAINT uq_scores_game_player UNIQUE (game_id, player_id)
);
