handlers=java.util.logging.ConsoleHandler
.level=INFO

uno.level=INFO
uno.useParentHandlers=true

java.util.logging.ConsoleHandler.level=INFO
java.util.logging.ConsoleHandler.formatter=java.util.logging.SimpleFormatter
